// Code generated by tygo. DO NOT EDIT.

//////////
// source: sqlite.go

export interface SQLiteStore {
}

//////////
// source: store.go

export interface Habit {
  id: number /* int64 */;
  name: string;
  schedule: string;
  createdAt: string;
  archived: boolean;
}
/**
 * CreateHabitRequest is the JSON body of POST /api/habits.
 */
export interface CreateHabitRequest {
  name: string;
  schedule: string;
}
/**
 * StreakResponse is returned for streak queries.
 */
export interface StreakResponse {
  streak: number /* int */;
}
export type Store = any;
